"""{Added badge table}

Revision ID: 65aa5353463a
Revises: 
Create Date: 2021-08-29 18:54:31.985509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65aa5353463a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_badges_id'), 'badges', ['id'], unique=True, schema='app')
    op.create_index(op.f('ix_app_badges_name'), 'badges', ['name'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_badges_name'), table_name='badges', schema='app')
    op.drop_index(op.f('ix_app_badges_id'), table_name='badges', schema='app')
    op.drop_table('badges', schema='app')
    # ### end Alembic commands ###
